"""Correlation cannot tell you the direction of causation -- X -> Y and Y -> X fit the same data equally well, and only an intervention distinguishes them, so a strong correlation never licenses 'change X to move Y'.

On this fixture the true structural model is Y -> X: Y is exogenous and X is caused by Y (X := slope*Y plus a small fixed perturbation). An analyst who only sees the two columns finds a strong correlation and is tempted to read a direction into it -- usually the one they expected -- and to act on it: 'X and Y move together, so to raise Y, raise X.'

The observational data does not contain that direction. For a simple linear relationship the coefficient of determination R-squared equals the squared correlation no matter which variable you regress on the other, so regressing Y on X and regressing X on Y fit the data identically. The fit is symmetric in the two variables; nothing in it distinguishes cause from effect. Both 'X drives Y' and 'Y drives X' explain the numbers exactly as well, which means the numbers explain neither.

What carries direction is intervention. In the true Y -> X model, X is downstream: the edge runs from Y to X and not back, so forcing X to a value externally -- cutting the Y -> X edge and setting X yourself -- leaves Y untouched, because nothing feeds from X back to Y. Forcing Y, on the other hand, changes X, because X is computed from Y. The asymmetry between these two experiments is the direction of the arrow, and it is invisible in the correlation.

So the naive reading is not just unproven, it is actionably wrong: an analyst who concludes X -> Y and intervenes on X to move Y will find Y does not move, because in reality Y drives X. Correlation earns you a relationship; only an intervention (or outside structural knowledge, or time order) earns you a direction.

This computes the correlation, the two identical regression fits, and the two intervention effects, showing the observational symmetry and the interventional asymmetry.

  --observe     the correlation and the R-squared of Y-on-X versus X-on-Y (identical)
  --intervene   the effect on Y of forcing X, versus the effect on X of forcing Y
  --check       the two regressions fit equally (correlation gives no direction); intervening on X does not move Y while intervening on Y moves X

y_values, slope, and noise are the fixture; the correlation, the regression fits, and the intervention effects are computed. Stdlib only.
"""
import argparse
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
DATA = HERE / "reversecause.json"


def load():
    return json.loads(DATA.read_text(encoding="utf-8"))


def observed_x(data):
    """The observational X, generated by the true model X := slope*Y + noise (Y -> X)."""
    return [data["slope"] * y + n for y, n in zip(data["y_values"], data["noise"])]


def correlation(a, b):
    n = len(a)
    ma, mb = sum(a) / n, sum(b) / n
    cov = sum((x - ma) * (y - mb) for x, y in zip(a, b))
    va = sum((x - ma) ** 2 for x in a)
    vb = sum((y - mb) ** 2 for y in b)
    return cov / (va * vb) ** 0.5


def r_squared(predictor, response):
    """R-squared of a simple linear regression of response on predictor."""
    return correlation(predictor, response) ** 2


def intervene_on_x(data, x_value):
    """do(X = x_value): cut the Y->X edge and set X. Y is exogenous, so it is unchanged."""
    return list(data["y_values"])          # Y does not depend on X; forcing X leaves Y as it is


def intervene_on_y(data, y_value):
    """do(Y = y_value): set Y; X is recomputed from the structural model X := slope*Y."""
    return data["slope"] * y_value         # X follows Y


# ----------------------------------------------------------------- printing

def observe_view(data):
    y = data["y_values"]
    x = observed_x(data)
    print("OBSERVE — the observational data (true model is Y -> X)")
    print("-" * 56)
    print("  Y = %s" % y)
    print("  X = %s" % [round(v, 2) for v in x])
    print("  correlation(X, Y) = %.4f" % correlation(x, y))
    print("  R^2 regressing Y on X = %.4f" % r_squared(x, y))
    print("  R^2 regressing X on Y = %.4f" % r_squared(y, x))
    print("-" * 56)
    print("  both regressions fit identically -- the data is symmetric, it names no direction")


def intervene_view(data):
    y = data["y_values"]
    print("INTERVENE — force one variable, see if the other moves")
    print("-" * 56)
    y_lo = intervene_on_x(data, 100)      # force X high
    y_hi = intervene_on_x(data, 200)      # force X higher
    eff_x_on_y = (sum(y_hi) / len(y_hi)) - (sum(y_lo) / len(y_lo))
    print("  do(X=100) -> mean(Y) = %.2f" % (sum(y_lo) / len(y_lo)))
    print("  do(X=200) -> mean(Y) = %.2f" % (sum(y_hi) / len(y_hi)))
    print("  effect of forcing X on Y = %.2f  (X is downstream; Y does not move)" % eff_x_on_y)
    eff_y_on_x = intervene_on_y(data, 4) - intervene_on_y(data, 3)
    print("  do(Y=3) -> X = %.2f ;  do(Y=4) -> X = %.2f" % (intervene_on_y(data, 3), intervene_on_y(data, 4)))
    print("  effect of forcing Y on X (per unit) = %.2f  (Y is the true cause)" % eff_y_on_x)
    print("-" * 56)
    print("  intervention is asymmetric where correlation was symmetric -- that asymmetry is the direction")


def check(data):
    print("SELF-TEST — the two regressions fit equally (correlation gives no direction); intervening on X does not move Y while intervening on Y moves X")
    print("-" * 112)
    y = data["y_values"]
    x = observed_x(data)

    corr_strong = abs(correlation(x, y)) > 0.9
    print("  X and Y are strongly correlated = %s (%.4f)" % (corr_strong, correlation(x, y)))

    fits_identical = abs(r_squared(x, y) - r_squared(y, x)) < 1e-12
    print("  regressing Y-on-X and X-on-Y fit identically = %s (%.4f == %.4f)" % (fits_identical, r_squared(x, y), r_squared(y, x)))

    eff_x_on_y = (sum(intervene_on_x(data, 200)) - sum(intervene_on_x(data, 100))) / len(y)
    forcing_x_does_not_move_y = abs(eff_x_on_y) < 1e-12
    print("  forcing X has no effect on Y = %s (effect %.4f)" % (forcing_x_does_not_move_y, eff_x_on_y))

    eff_y_on_x = intervene_on_y(data, 4) - intervene_on_y(data, 3)
    forcing_y_moves_x = abs(eff_y_on_x) > 0
    print("  forcing Y does change X = %s (effect %.2f per unit)" % (forcing_y_moves_x, eff_y_on_x))

    intervention_breaks_symmetry = forcing_x_does_not_move_y and forcing_y_moves_x
    print("  intervention is asymmetric though the correlation was symmetric = %s" % intervention_breaks_symmetry)

    ok = (corr_strong and fits_identical and forcing_x_does_not_move_y
          and forcing_y_moves_x and intervention_breaks_symmetry)
    print("-" * 112)
    print("SELF-TEST %s  corr_strong=%s  fits_identical=%s  forcing_x_does_not_move_y=%s  forcing_y_moves_x=%s  intervention_breaks_symmetry=%s"
          % ("PASS" if ok else "FAIL", corr_strong, fits_identical, forcing_x_does_not_move_y,
             forcing_y_moves_x, intervention_breaks_symmetry))
    return ok


def main():
    p = argparse.ArgumentParser(description="Reverse causation: correlation cannot tell you the direction of causation -- X -> Y and Y -> X fit the same data equally (R-squared is identical both ways), and only an intervention distinguishes them, so a strong correlation never licenses 'change X to move Y'.")
    p.add_argument("--observe", action="store_true")
    p.add_argument("--intervene", action="store_true")
    p.add_argument("--check", action="store_true")
    args = p.parse_args()

    data = load()
    print("y_values=%s  slope=%.1f  file=%s  (these are a fixture; true model Y -> X)"
          % (data["y_values"], data["slope"], DATA.name))
    print("")

    if args.check:
        return 0 if check(data) else 1
    if args.observe:
        observe_view(data)
    elif args.intervene:
        intervene_view(data)
    else:
        p.print_help()
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
